### pobranie listy wszystkich ofert
GET http://localhost:8080/api/offers

### pobranie oferty za pomocą wskazania danego ID
GET http://localhost:8080/api/offers/7

### dodanie nowej oferty
POST http://localhost:8080/api/offers
Content-Type: application/json

{
  "name": "Pożyczka nowa",
  "minimumAmount": 1000.00,
  "maximumAmount": 250000.00,
  "rrso": 12.00,
  "commissionPercent": 4.00,
  "periodInMonths": 120,
  "url": "https://www.pekao.com.pl/klient-indywidualny/pozyczanie-gotowki/pozyczka-na-dowolny-cel.html",
  "bank": {
    "id": 3,
    "name": "Bank Pekao"
  },
  "typeOfLoan": {
    "id": 3,
    "name_Type": "pożyczka gotówkowa"
  }
}

### update danego banku za pośrednictwem wyboru danego ID
PUT http://localhost:8080/api/offers/13
Content-Type: application/json

{
  "name": "Pożyczka nowa",
  "minimumAmount": 1000.00,
  "maximumAmount": 250000.00,
  "rrso": 12.00,
  "commissionPercent": 4.00,
  "periodInMonths": 120,
  "url": "https://www.pekao.com.pl/klient-indywidualny/pozyczanie-gotowki/pozyczka-na-dowolny-cel.html",
  "bank": {
    "id": 3,
    "name": "Bank Pekao"
  },
  "typeOfLoan": {
    "id": 3,
    "name_Type": "pożyczka gotówkowa"
  }
}

### usunięcie danego banku rozróżniając go po ID
DELETE http://localhost:8080/api/offers/12

### 3 oferty z najniższym RRSO
GET http://localhost:8080/api/offers/lowest-rrso


### 3 oferty z najniższą prowizją
GET http://localhost:8080/api/offers/lowest-commission


### oferty spełniające wymóg znajdowania się w 3 ofert z najniższym RRSO i najniższą prowizją
GET http://localhost:8080/api/offers/matching-offers

