### "logowanie" klienta - podanie jego danych

POST http://localhost:8080/client
Content-Type: application/json

{
  "first_Name": "Test2",
  "second_Name": "Test2",
  "email": "CreditOffer1@outlook.com"
}

### filtr ofert

POST http://localhost:8080/api/searchHistory/offers/filter
Content-Type: application/json

{
  "amount": 1000,
  "maxRrso": 13,
  "maxCommissionPercent": 6,
  "maxPeriodInMonths": 360,
  "client": {
    "id": 1
  }
}